server:
  port: 8089

spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://localhost:5432/pd_test
    username: root
    password: root
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.type: true
      hibernate.use_sql_comments: true
  kafka:
    admin:
      properties:
        offsets.topic.replication.factor: 1
        transaction.state.log.replication.factor: 1
        transaction.state.log.min.isr: 1
    bootstrapServers:
      - localhost:9092
    topics:
      - name: "payment-command"
        partitions: 1
        replication-factor: 1
      - name: "payment-command-result"
        partitions: 1
        replication-factor: 1
  data:
    redis:
      host: localhost
      port: 6379
      password: redis
      username: default
  cache:
    type: redis

logging:
  level:
    org.hibernate.type.descriptor.sql: TRACE

currencyfreaks:
  api:
    key: 465eadc1dd6e401fbaff4711b73892f8           # забирается из env
    url: https://api.currencyfreaks.com/v2.0/rates/    # базовый URL
